VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # ファイル共有の設定
  config.vm.synced_folder "host_dir/", "/guest_dir"

  # ネットワーク設定
  config.vm.network :forwarded_port, guest: 80, host: 8080

end

