VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define "web_server" do |web|
    web.vm.network :private_network, ip: "192.168.33.10"
    web.vm.provision :shell, path: "web_provision.sh"
  end

  config.vm.define "db_server" do |db|
    db.vm.network :private_network, ip: "192.168.33.11"
    db.vm.provision :shell, path: "db_provision.sh"
  end
end

